# Site settings
title: "jzuern.github.io"
description:
  A playground for everything interesting and irrelevant.

author: Jannik Zürn
email: jannik.zuern@gmail.com
twitter_username: 
github_username: jzuern
linkedin_name: jannik-zürn-725497a4/
scholar_profile: jannik-zürn-725497a4/

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jzuern.github.io" # the base hostname & protocol for your site

google_analytics_id:
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

background-image: url('/about/assets/me.jpg')



# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: wrgwrgrwgw
    
